repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v5.0.0
      hooks:
          - id: end-of-file-fixer
          - id: trailing-whitespace
          - id: check-yaml
            exclude: |
                (?x)^(
                    docker-compose.yml
                )
          - id: check-json
          - id: check-merge-conflict
          - id: mixed-line-ending

    - repo: https://github.com/astral-sh/ruff-pre-commit
      rev: v0.11.0
      hooks:
          # Run the linter, and enable lint fixes
          - id: ruff
            args: [--fix]
          # Run the formatter.
          - id: ruff-format
