sudo: false
language: python
python:
- '3.6'
env:
- DJANGO_SETTINGS_MODULE="visualizing_russian_tools.settings.local" BOTO_CONFIG=/dev/null
install:
- pip install pipenv
- pipenv install
script:
- pipenv run python3 manage.py migrate --noinput
- pipenv run python3 manage.py test