version: '3'

services:
  web:
    build: .
    image: visualizing_russian_tools
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=visualizing_russian_tools.settings.aws
      - DJANGO_SECRET_KEY=asdfaafl;kjl;k2j3423
      - DJANGO_LOG_LEVEL=DEBUG
      - LOG_LEVEL=DEBUG
      - DB_LOG_LEVEL=DEBUG
      - SENTRY_DEBUG=1
      - SENTRY_DSN=""

