name: Lint

on:
  push:
    branches: [ main, master ]
    paths:
      - '**.py'
      - 'requirements*.txt'
      - '.github/workflows/lint.yml'
  pull_request:
    paths:
      - '**.py'
      - 'requirements*.txt'
      - '.github/workflows/lint.yml'

jobs:
  lint:
    runs-on: arc-runner-set-com
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11' # From Dockerfile
          
      - name: Install ruff
        # No need for all the dependencies
        run: |
          pip install ruff
          
      - name: Run ruff for Python formatting check
        run: ruff format --check .

      - name: Run ruff for Python linting check
        run: ruff check .