name: Tests

on:
  push:
    branches: [ main, master ]
    paths:
      - '**.py'
      - 'requirements*.txt'
      - '.github/workflows/tests.yml'
  pull_request:
    paths:
      - '**.py'
      - 'requirements*.txt'
      - '.github/workflows/tests.yml'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run unit tests
        run: |
          python manage.py test

      # TODO run the Jasmine JS tests

      # TODO update coverage badge if merging into main
